language: node_js
node_js:
    - "0.10"
    - "4.2"
    - "5.0"

services:

matrix:
    allow_failures:
        - node_js: "5.0"

after_success:
    - npm install istanbul codecov.io
    - NODE_ENV=cov ./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha -- -R spec
    - cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js

sudo: false
